  AddCatalogItem(0, 'SAPI 5', '', 'sapi5', '', '', '');
  AddCatalogItem(0, 'Speech Platform', '', 'speech_platform', '', '', '');
  AddCatalogItem(0, 'ML / AI', '', 'ml', '', '', '');
  AddCatalogItem(1, '  Kokoro-82M', '~300 MB', 'ml', 'kokoro', '', '');
  AddCatalogItem(2, '    American F · Heart', '~0.2 MB', 'ml', 'kokoro', 'af_heart', 'sample_ml_kokoro_af_heart.mp3');
  AddCatalogItem(2, '    American F · Bella', '~0.2 MB', 'ml', 'kokoro', 'af_bella', 'sample_ml_kokoro_af_bella.mp3');
  AddCatalogItem(2, '    American F · Nicole', '~0.3 MB', 'ml', 'kokoro', 'af_nicole', 'sample_ml_kokoro_af_nicole.mp3');
  AddCatalogItem(2, '    American M · Adam', '~0.2 MB', 'ml', 'kokoro', 'am_adam', 'sample_ml_kokoro_am_adam.mp3');
  AddCatalogItem(2, '    American M · Michael', '~0.2 MB', 'ml', 'kokoro', 'am_michael', 'sample_ml_kokoro_am_michael.mp3');
  AddCatalogItem(2, '    British F · Emma', '~0.2 MB', 'ml', 'kokoro', 'bf_emma', 'sample_ml_kokoro_bf_emma.mp3');
  AddCatalogItem(2, '    British M · George', '~0.2 MB', 'ml', 'kokoro', 'bm_george', 'sample_ml_kokoro_bm_george.mp3');
  AddCatalogItem(1, '  Piper', '', 'ml', 'piper', '', '');
  AddCatalogItem(2, '    Lessac US M · Medium', '~0.1 MB', 'ml', 'piper', 'en_US-lessac-medium', 'sample_ml_piper_en_US-lessac-medium.mp3');
  AddCatalogItem(2, '    Amy US F · Medium', '~0.2 MB', 'ml', 'piper', 'en_US-amy-medium', 'sample_ml_piper_en_US-amy-medium.mp3');
  AddCatalogItem(2, '    Ryan US M · High', '~0.1 MB', 'ml', 'piper', 'en_US-ryan-high', 'sample_ml_piper_en_US-ryan-high.mp3');
  AddCatalogItem(2, '    Kathleen US F · Low', '~0.2 MB', 'ml', 'piper', 'en_US-kathleen-low', 'sample_ml_piper_en_US-kathleen-low.mp3');
  AddCatalogItem(2, '    Southern GB F · Low', '~0.1 MB', 'ml', 'piper', 'en_GB-southern_english_female-low', 'sample_ml_piper_en_GB-southern_english_female-low.mp3');
  AddCatalogItem(2, '    Jenny GB F · Medium', '~0.2 MB', 'ml', 'piper', 'en_GB-jenny_dioco-medium', 'sample_ml_piper_en_GB-jenny_dioco-medium.mp3');
  AddCatalogItem(2, '    Alan GB M · Medium', '~0.2 MB', 'ml', 'piper', 'en_GB-alan-medium', 'sample_ml_piper_en_GB-alan-medium.mp3');
  AddCatalogItem(1, '  Chatterbox 0.5B', '~2000 MB', 'ml', 'chatterbox', '', '');
  AddCatalogItem(2, '    Default', '~0.1 MB', 'ml', 'chatterbox', 'default', 'sample_ml_chatterbox_default.mp3');
  AddCatalogItem(2, '    Female · Calm', '~0.2 MB', 'ml', 'chatterbox', 'female_calm', 'sample_ml_chatterbox_female_calm.mp3');
  AddCatalogItem(2, '    Male · Warm', '~0.2 MB', 'ml', 'chatterbox', 'male_warm', 'sample_ml_chatterbox_male_warm.mp3');
  AddCatalogItem(1, '  Dia 1.6B', '~3500 MB', 'ml', 'dia', '', '');
  AddCatalogItem(2, '    [S1] Speaker 1', '~0.7 MB', 'ml', 'dia', 's1', 'sample_ml_dia_s1.mp3');
  AddCatalogItem(2, '    [S2] Speaker 2', '~0.2 MB', 'ml', 'dia', 's2', 'sample_ml_dia_s2.mp3');
  AddCatalogItem(1, '  F5-TTS', '~1200 MB', 'ml', 'f5tts', '', '');
  AddCatalogItem(2, '    English F · Calm', '~0.2 MB', 'ml', 'f5tts', 'en_female_calm', 'sample_ml_f5tts_en_female_calm.mp3');
  AddCatalogItem(2, '    English M · Warm', '~0.2 MB', 'ml', 'f5tts', 'en_male_warm', 'sample_ml_f5tts_en_male_warm.mp3');
  AddCatalogItem(1, '  OuteTTS 0.5B', '~1000 MB', 'ml', 'outetts', '', '');
  AddCatalogItem(2, '    Male 1', '~0.2 MB', 'ml', 'outetts', 'male_1', 'sample_ml_outetts_male_1.mp3');
  AddCatalogItem(2, '    Male 2', '~0.2 MB', 'ml', 'outetts', 'male_2', 'sample_ml_outetts_male_2.mp3');
  AddCatalogItem(2, '    Male 3', '~0.1 MB', 'ml', 'outetts', 'male_3', 'sample_ml_outetts_male_3.mp3');
  AddCatalogItem(2, '    Female 1', '~0.2 MB', 'ml', 'outetts', 'female_1', 'sample_ml_outetts_female_1.mp3');
  AddCatalogItem(1, '  VibeVoice-Realtime 0.5B', '~2000 MB', 'ml', 'vibevoice_realtime', '', '');
  AddCatalogItem(2, '    Carter (M)', '~0.2 MB', 'ml', 'vibevoice_realtime', 'carter', 'sample_ml_vibevoice_realtime_carter.mp3');
  AddCatalogItem(2, '    Davis (M)', '~0.2 MB', 'ml', 'vibevoice_realtime', 'davis', 'sample_ml_vibevoice_realtime_davis.mp3');
  AddCatalogItem(2, '    Frank (M)', '~0.2 MB', 'ml', 'vibevoice_realtime', 'frank', 'sample_ml_vibevoice_realtime_frank.mp3');
  AddCatalogItem(2, '    Mike (M)', '~0.1 MB', 'ml', 'vibevoice_realtime', 'mike', 'sample_ml_vibevoice_realtime_mike.mp3');
  AddCatalogItem(2, '    Emma (F)', '~0.2 MB', 'ml', 'vibevoice_realtime', 'emma', 'sample_ml_vibevoice_realtime_emma.mp3');
  AddCatalogItem(2, '    Grace (F)', '~0.2 MB', 'ml', 'vibevoice_realtime', 'grace', 'sample_ml_vibevoice_realtime_grace.mp3');
