Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/af_heart.mp3"; DestName: "sample_ml_kokoro_af_heart.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/af_bella.mp3"; DestName: "sample_ml_kokoro_af_bella.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/af_nicole.mp3"; DestName: "sample_ml_kokoro_af_nicole.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/am_adam.mp3"; DestName: "sample_ml_kokoro_am_adam.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/am_michael.mp3"; DestName: "sample_ml_kokoro_am_michael.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/bf_emma.mp3"; DestName: "sample_ml_kokoro_bf_emma.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/kokoro/bm_george.mp3"; DestName: "sample_ml_kokoro_bm_george.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_US-lessac-medium.mp3"; DestName: "sample_ml_piper_en_US-lessac-medium.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_US-amy-medium.mp3"; DestName: "sample_ml_piper_en_US-amy-medium.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_US-ryan-high.mp3"; DestName: "sample_ml_piper_en_US-ryan-high.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_US-kathleen-low.mp3"; DestName: "sample_ml_piper_en_US-kathleen-low.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_GB-southern_english_female-low.mp3"; DestName: "sample_ml_piper_en_GB-southern_english_female-low.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_GB-jenny_dioco-medium.mp3"; DestName: "sample_ml_piper_en_GB-jenny_dioco-medium.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/piper/en_GB-alan-medium.mp3"; DestName: "sample_ml_piper_en_GB-alan-medium.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/chatterbox/default.mp3"; DestName: "sample_ml_chatterbox_default.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/chatterbox/female_calm.mp3"; DestName: "sample_ml_chatterbox_female_calm.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/chatterbox/male_warm.mp3"; DestName: "sample_ml_chatterbox_male_warm.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/dia/s1.mp3"; DestName: "sample_ml_dia_s1.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/dia/s2.mp3"; DestName: "sample_ml_dia_s2.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/f5tts/en_female_calm.mp3"; DestName: "sample_ml_f5tts_en_female_calm.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/f5tts/en_male_warm.mp3"; DestName: "sample_ml_f5tts_en_male_warm.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/outetts/male_1.mp3"; DestName: "sample_ml_outetts_male_1.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/outetts/male_2.mp3"; DestName: "sample_ml_outetts_male_2.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/outetts/male_3.mp3"; DestName: "sample_ml_outetts_male_3.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/outetts/female_1.mp3"; DestName: "sample_ml_outetts_female_1.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/carter.mp3"; DestName: "sample_ml_vibevoice_realtime_carter.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/davis.mp3"; DestName: "sample_ml_vibevoice_realtime_davis.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/frank.mp3"; DestName: "sample_ml_vibevoice_realtime_frank.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/mike.mp3"; DestName: "sample_ml_vibevoice_realtime_mike.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/emma.mp3"; DestName: "sample_ml_vibevoice_realtime_emma.mp3"; Flags: dontcopy ignoreversion
Source: "{#DistDir}\_internal\install\assets\audio\ml/vibevoice_realtime/grace.mp3"; DestName: "sample_ml_vibevoice_realtime_grace.mp3"; Flags: dontcopy ignoreversion
